local map = vim.keymap.set

map("n", "<leader>w", ":w<CR>")
map("n", "<leader>q", ":q<CR>")
map("n", "<C-h>", "<C-w>h")
map("n", "<C-j>", "<C-w>j")
map("n", "<C-k>", "<C-w>k")
map("n", "<C-l>", "<C-w>l")
map("n", "<Esc>", ":noh<CR>")
map("n", "<leader>e", ":NvimTreeToggle<CR>")
map("n", "<leader>ff", ":Telescope find_files<CR>")
map("n", "<leader>fg", ":Telescope live_grep<CR>")
map("n", "<leader>fb", ":Telescope buffers<CR>")
map("n", "<leader>gp", ":Gitsign preview_hunk<CR>")
map("n", "<leader>gs", ":Gitsign stage_hunk<CR>")
map("n", "<leader>gh", ":Gitsign nav_hunk next<CR>")
map("n", "<leader>gl", ":Gitsign nav_hunk preview<CR>")
