# Índice de base das janelas começando em 1
set -g base-index 1

# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Splits intuitivos
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Navegação vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Mouse support
set -g mouse on

# Configuração do sessionx
set -g @sessionx-bind 'o'
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-filter-current 'false'

# Plugins
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin '2kabhishek/tmux2k'

set -g @continuum-restore 'on' # Enables automatic restoration on Tmux server start
set -g @continuum-save-interval '15' # Adjusts auto-save interval (in minutes)
# TPM - carregar plugins ANTES das configurações
run '~/.tmux/plugins/tpm/tpm'


# use a theme
set -g @tmux2k-theme 'duo'
set -g @tmux2k-icons-only false
set -g @tmux2k-show-powerline true

# deixe o duo padrão:
# não coloque @tmux2k-duo-fg
# não coloque @tmux2k-duo-bg

# layout padrão do tmux2k
set -g @tmux2k-left-plugins "session git cwd"
set -g @tmux2k-right-plugins "cpu ram battery network time"

set -g @tmux2k-window-list-alignment "absolute-centre"
set -g @tmux2k-window-list-format "#I:#W"

set -g @tmux2k-window-list-left-sep ""
set -g @tmux2k-window-list-right-sep ""
# Reload
unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux.conf recarregado"

# Disable mouse selection in copy mode
unbind -T copy-mode-vi MouseDragEnd1Pane
